RailsProject/Booking/config/routes.rb
Booking::Application.routes.draw do
  resources :reserves

  resources :signups

  resources :rooms

  resources :hotels

	match '/searchHotel', :to => 'hotels#search'
	match '/viewHotel', :to => 'hotels#found'
	match '/avilableRooms/:id', :to => 'rooms#found'
	match '/reservedRoom/:id', :to => 'rooms#reserved'
	match '/register', :to => 'signups#new'
	match '/login', :to => 'signups#login'
	match '/logout', :to => 'signups#logOut'
	match '/loginBook', :to => 'signups#loginBook'
	match '/loginComment', :to => 'signups#loginComment'
	match '/reserved', :to => 'rooms#reserved'
	match '/viewdetail/:id', :to => 'rooms#viewdetail'
	match '/addcomment/:id', :to => 'rooms#addcomment'
	match '/searchComment', :to => 'hotels#searchComment'
	match '/roomComment', :to => 'hotels#roomComment'

end

RailsProject/Booking/app/models/signup.rb
class Signup < ActiveRecord::Base
	validates :name, :presence => true
	validates :email, :presence => true
	validates :password, :presence => true
	validates :phone, :presence => true
end

RailsProject/Booking/app/controllers/signups_controller.rb
require 'digest/md5'

class SignupsController < ApplicationController
  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signups }
    end
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
    @signup = Signup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signup }
    end
  end

  # GET /signups/new
  # GET /signups/new.json
  def new
    @signup = Signup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signup }
    end
  end

  # GET /signups/1/edit
  def edit
    @signup = Signup.find(params[:id])
  end

  # POST /signups
  # POST /signups.json
  def create
    	hashPassword= Digest::MD5.hexdigest(params[:signup][:password])
		newParams={"name" => params[:signup][:name], "email" => params[:signup][:email], "password" => hashPassword, "phone" => params[:signup][:phone] }
		@signup = Signup.new(newParams)
    respond_to do |format|
      if @signup.save
				@first = "first"
				format.html { render action: "login" }
        #format.html { redirect_to @signup, notice: hashPassword }
        format.json { render json: @signup, status: :created, location: @signup }
      else
        format.html { render action: "new" }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /signups/1
  # PUT /signups/1.json
  def update
   @signup = Signup.find(params[:id])

    respond_to do |format|
      if @signup.update_attributes(params[:signup])
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup = Signup.find(params[:id])
    @signup.destroy

    respond_to do |format|
      format.html { redirect_to signups_url }
      format.json { head :no_content }
    end
  end

	def login
		@email = params[:email]
		@password = params[:password]
		
		
		if @email
				hashPassword= Digest::MD5.hexdigest(params[:password])
				@user = Signup.find_by_sql(["select * from signups where email=? and password=?",params[:email],hashPassword])
				if @user.size > 0
					for user in @user
						cookies[:login] = { value: user.id, expires: 1.hour.from_now }
						#cookies.delete(:login)
						redirect_to url_for(:controller => 'hotels',:action => 'search')
					end
				else
					@notfound="the user u enter not found please try again"
				end
		end
	end
#---------------------------------------------
	def loginBook
		@email = params[:email]
		@password = params[:password]
		
		
		if @email
				hashPassword= Digest::MD5.hexdigest(params[:password])
				@user = Signup.find_by_sql(["select * from signups where email=? and password=?",params[:email],hashPassword])
				if @user.size > 0
					for user in @user
						cookies[:login] = { value: user.id, expires: 1.hour.from_now }
						j=0
						while j < cookies[:count].to_i
						#cookies.delete(:login)
							newParams={"user_id" => cookies[:login] , "hotel_id" => cookies[:hotel_id1], "room_id" => cookies[j], "check_in" => cookies[:checkIn1], "check_out" => cookies[:checkOut1]  }
							@reserve = Reserve.new(newParams)
							@reserve.save
							j+=1
						end
						redirect_to url_for(:controller => 'hotels',:action => 'search')						
					end
					
				else
					@notfound="the user u enter not found please try again"
				end
		end
	end
#--------------------------------------
	def logOut
			cookies.delete(:login)
			redirect_to url_for(:controller => 'hotels',:action => 'search')	
	end
#----------------------------------------
	def loginComment

	@email = params[:email]
	@password = params[:password]
		
	if @email
			hashPassword= Digest::MD5.hexdigest(params[:password])
			@user = Signup.find_by_sql(["select * from signups where email=? and password=?",params[:email],hashPassword])
			if @user.size > 0
				for user in @user
					cookies[:login] = { value: user.id, expires: 1.hour.from_now }
					#cookies.delete(:login)
						newParams={"user_id" => cookies[:login] , "hotel_id" => cookies[:hotel_id1], "room_id" => cookies[:room_id1], "comment" =>cookies[:comment1] }
						@reserve = Comment.new(newParams)
						@reserve.save
					redirect_to url_for(:controller => 'hotels',:action => 'search')						
				end
				
			else
				@notfound="the user u enter not found please try again"
			end
	end

	end
#----------------------------------------
end

RailsProject/Booking/app/helpers/signups_helper.rb
module SignupsHelper
end

RailsProject/Booking/app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsProject/Booking/app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

RailsProject/Booking/app/views/signups/index.html.erb
<h1>Listing signups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signups.each do |signup| %>
  <tr>
    <td><%= signup.name %></td>
    <td><%= signup.email %></td>
    <td><%= signup.password %></td>
    <td><%= signup.phone %></td>
    <td><%= link_to 'Show', signup %></td>
    <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
    <td><%= link_to 'Destroy', signup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signup', new_signup_path %>

RailsProject/Booking/app/views/signups/log.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>



<h1>Login</h1>
<%= session["user_id"] %>
<form action="/login" method="post">
  <fieldset>
    <legend>Personalia:</legend>
		<input type="text" id="h1" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Email:<input type="email" name="email" id="e" value=<%=@email%> >
		<br>	
		<input type="text" id="h2" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Password: <input type="password" name="password" id="p" value=<%=@password%> >
		<br>	
		
		<input type="submit" value="login" id="s">
	</fieldset>

</form>

<script>
		sub=document.getElementById("s");
		email = document.getElementById("e");
		password = document.getElementById("p");
		error1 = document.getElementById("h1");
		error2 = document.getElementById("h2");
		sub.addEventListener('click',function(e){
			error1.value=""
			error2.value=""
			if (email.value == ""){
				e.preventDefault();
				error1.value="enter your email"
			}
				if (password.value == ""){
				e.preventDefault();
				error2.value="enter your password"
			}
		});
</script>
</html>

RailsProject/Booking/app/views/signups/login.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>


<h1>Login</h1>
<%= @notfound %>
<% @first %>
	<% if @first == "first"%>
 		<script> window.location.href = "/login" </script>
	<%end%>
<form action="/login" method="post">
  <fieldset>
    <legend>Personalia:</legend>
		<input type="text" id="h1" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Email:<input type="email" name="email" id="e" value=<%=@email%> >
		<br>	
		<input type="text" id="h2" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Password: <input type="password" name="password" id="p" value=<%=@password%> >
		<br>	
		
		<input type="submit" value="login" id="s">
	</fieldset>

</form>

<script>
		sub=document.getElementById("s");
		email = document.getElementById("e");
		password = document.getElementById("p");
		error1 = document.getElementById("h1");
		error2 = document.getElementById("h2");
		sub.addEventListener('click',function(e){
			error1.value=""
			error2.value=""
			if (email.value == ""){
				e.preventDefault();
				error1.value="enter your email"
			}
				if (password.value == ""){
				e.preventDefault();
				error2.value="enter your password"
			}
		});
</script>
</html>

RailsProject/Booking/app/views/signups/loginBook.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>

<h1>Login</h1>
<%= @notfound %>
<% @first %>
	<% if @first == "first"%>
 		<script> window.location.href = "/loginBook" </script>
	<%end%>
<form action="/loginBook" method="post">
  <fieldset>
    <legend>Personalia:</legend>
		<input type="text" id="h1" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Email:<input type="email" name="email" id="e" value=<%=@email%> >
		<br>	
		<input type="text" id="h2" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Password: <input type="password" name="password" id="p" value=<%=@password%> >
		<br>	
		
		<input type="submit" value="login" id="s">
	</fieldset>

<%=cookies[:count] %>
</form>

<script>
		sub=document.getElementById("s");
		email = document.getElementById("e");
		password = document.getElementById("p");
		error1 = document.getElementById("h1");
		error2 = document.getElementById("h2");
		sub.addEventListener('click',function(e){
			error1.value=""
			error2.value=""
			if (email.value == ""){
				e.preventDefault();
				error1.value="enter your email"
			}
				if (password.value == ""){
				e.preventDefault();
				error2.value="enter your password"
			}
		});
</script>
</html>

RailsProject/Booking/app/views/signups/loginComment.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>

<h1>Login Comment</h1>
<%= @notfound %>
<% @first %>
	<% if @first == "first"%>
 		<script> window.location.href = "/loginComment" </script>
	<%end%>
<form action="/loginComment" method="post">
  <fieldset>
    <legend>Personalia:</legend>
		<input type="text" id="h1" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Email:<input type="email" name="email" id="e" value=<%=@email%> >
		<br>	
		<input type="text" id="h2" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Password: <input type="password" name="password" id="p" value=<%=@password%> >
		<br>	
		
		<input type="submit" value="login" id="s">
	</fieldset>

<%=cookies[:count] %>
</form>

<script>
		sub=document.getElementById("s");
		email = document.getElementById("e");
		password = document.getElementById("p");
		error1 = document.getElementById("h1");
		error2 = document.getElementById("h2");
		sub.addEventListener('click',function(e){
			error1.value=""
			error2.value=""
			if (email.value == ""){
				e.preventDefault();
				error1.value="enter your email"
			}
				if (password.value == ""){
				e.preventDefault();
				error2.value="enter your password"
			}
		});
</script>
</html>

RailsProject/Booking/app/views/signups/new.html.erb
<h1>New signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

RailsProject/Booking/app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @signup.name %>
</p>

<p>
  <b>Email:</b>
  <%= @signup.email %>
</p>

<p>
  <b>Password:</b>
  <%= @signup.password %>
</p>

<p>
  <b>Phone:</b>
  <%= @signup.phone %>
</p>


<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>