RailsProject/Booking/config/routes.rb
Booking::Application.routes.draw do
  resources :reserves

  resources :signups

  resources :rooms

  resources :hotels

	match '/searchHotel', :to => 'hotels#search'
	match '/viewHotel', :to => 'hotels#found'
	match '/avilableRooms/:id', :to => 'rooms#found'
	match '/reservedRoom/:id', :to => 'rooms#reserved'
	match '/register', :to => 'signups#new'
	match '/login', :to => 'signups#login'
	match '/logout', :to => 'signups#logOut'
	match '/loginBook', :to => 'signups#loginBook'
	match '/loginComment', :to => 'signups#loginComment'
	match '/reserved', :to => 'rooms#reserved'
	match '/viewdetail/:id', :to => 'rooms#viewdetail'
	match '/addcomment/:id', :to => 'rooms#addcomment'
	match '/searchComment', :to => 'hotels#searchComment'
	match '/roomComment', :to => 'hotels#roomComment'

end

RailsProject/Booking/app/models/hotel.rb
class Hotel < ActiveRecord::Base
	has_many :rooms
end

RailsProject/Booking/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController


  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
	
	def search
		
		cookies.delete(:country1)
		cookies.delete(:checkIn1)
		cookies.delete(:checkOut1)
		cookies.delete(:hotel_id1)
		@country=params[:country]
		@checkIn=params[:checkIn]
		@checkOut=params[:checkOut]
		
	
		#@hotel=Hotel.find_by_country("cairo")
		#@users = Hotel.find_by_sql(["SELECT * FROM hotels where country = ? ",@country])
			if @country
				#for user in @users
				#		@new=user.id
				#end
				#session[:country] = @country
				#session[:checkIn] = @checkIn
				#session[:checkOut] = @checkOut
				

				if Date.parse(params[:checkIn]) < Date.today
					cookies[:error1] = { value: "the check in date is in past", expires: 1.hour.from_now }
					redirect_to url_for(:controller => 'hotels',:action => 'search')
				else				
					if Date.parse(params[:checkOut]) > Date.parse(params[:checkIn]) 
						cookies.delete(:error1)
						cookies[:checkIn1] = { value: params[:checkIn], expires: 1.hour.from_now }
						cookies[:checkOut1] = { value: params[:checkOut], expires: 1.hour.from_now }
						cookies[:country1] = { value: params[:country], expires: 1.hour.from_now }

				   redirect_to url_for(:controller => 'hotels',:action => 'found')
					else
						cookies[:error1] = { value: "the check out must be > check in", expires: 1.hour.from_now }

						redirect_to url_for(:controller => 'hotels',:action => 'search')
					end
				end
			end 
	end 
	
	def found
			if cookies[:country1].blank?
				redirect_to url_for(:controller => 'hotels',:action => 'search')
			else
				@hotels = Hotel.find_by_sql(["SELECT * FROM hotels where country = ? ",cookies[:country1]])
				for hotel in @hotels
					@city=hotel.city
					@address=hotel.address
					@name=hotel.name
				end
			end
	end

#------------------------------------------------------------
	def searchComment
		@hotelName = params[:hotel]
		@region = params[:region]
			if @hotelName
		
				#cookies[:hotelName2] = { value: params[:hotel], expires: 1.hour.from_now }
				#cookies[:region2] = { value: params[:region], expires: 1.hour.from_now }
				@hotels = Hotel.find_by_sql(["SELECT * FROM hotels where name = ? and region = ?",@hotelName,@region])
				if @hotels.size>0
					for hotel in @hotels 
						cookies[:hotel_id1] = hotel.id
					end 

		  		redirect_to url_for(:controller => 'hotels',:action => 'roomComment')	

				else
					cookies[:error1] = { value: "no available hotel", expires: 1.hour.from_now }
					redirect_to url_for(:controller => 'hotels',:action => 'searchComment')
				end			
			end
	end
#-------------------------------------------------------------
	def roomComment
			@rooms = Room.find_by_sql(["SELECT * FROM rooms where hotel_id = ?",cookies[:hotelid2]])	

	end
#-----------------------------------------------------------------
end

RailsProject/Booking/app/helpers/hotels_helper.rb
module HotelsHelper
end

RailsProject/Booking/app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsProject/Booking/app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

RailsProject/Booking/app/views/hotels/found.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>


<table border="1" style="width:300px">
	<tr>
		<td> hotel Name </td>
		<td> city </td>
		<td> address </td>
	</tr>
	<% if @hotels.size > 0 %>
		<% @hotels.each do |hotel| %>
			<tr>
				<td> <a href = "/avilableRooms/<%= hotel.id%>"> <%= hotel.name%> </a>
				<td> <%= hotel.city%> </td>
				<td> <%= hotel.address%> </td>
			</tr>
		<%end%>
	<%else%>
		<a href="javascript:history.back()"> no hotel available in this country </a>
	<%end%>

</table>

<%=cookies[:login]%>

<%=cookies[:country1]%>


</body>

RailsProject/Booking/app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Country</th>
    <th>City</th>
    <th>Region</th>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.country %></td>
    <td><%= hotel.city %></td>
    <td><%= hotel.region %></td>
    <td><%= hotel.name %></td>
    <td><%= hotel.address %></td>
    <td><%= hotel.phone %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel', new_hotel_path %>

RailsProject/Booking/app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

RailsProject/Booking/app/views/hotels/roomComment.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>




<form action="/reserved" method="post">
	<%= session[:hotel_id] %>
		
	<%= session[:checkIn] %>
	<% if @rooms.size > 0 %>
	<table border="1" style="width:300px">
	<tr>
		<td> Room Number </td>
		<td> Room Price </td>
		<td> Room Service </td>
	</tr>
		<% @rooms.each do |room| %>
			<tr>
				<td> <a href = "/viewdetail/<%= room.room_number%>"> <%= room.room_number%> </a> </td>
				<td>  <%= room.room_price%> </td>
				<td>  <%= room.room_service%> </td>	
			</tr>
		<%end%>
		</table>
	<%else%>
		<a href="javascript:history.back()"> no hotel available in this country </a>
	<%end%>

</form>

</body>

RailsProject/Booking/app/views/hotels/search.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>


<form action="/searchHotel" method="post">
  <fieldset>
    <legend>Personalia:</legend>
		<input type="text" id="h1" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Country:<input type="text" name="country" id="c" value=<%=@country%> >
		<br>	
		<input type="text" id="h2" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Check In: <input type="date" name="checkIn" id="ci" value=<%=@checkIn%> >
		<br>	
		<input type="text" id="h3" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Check Out: <input type="date" name="checkOut" id="co" value=<%=@checkOut%> >
		<br>
		<input type="submit" value="Search" id="s">
	</fieldset>

</form>
<%=cookies[:error1] %>
<script>
		sub=document.getElementById("s");
		country = document.getElementById("c");
		CheckIn = document.getElementById("ci");
		CheckOut = document.getElementById("co");
		error1 = document.getElementById("h1");
		error2 = document.getElementById("h2");
		error3 = document.getElementById("h3");
		sub.addEventListener('click',function(e){
			error1.value=""
			error2.value=""
			error3.value=""
			if (country.value == ""){
				e.preventDefault();
				error1.value="choose the country"
			}
				if (CheckIn.value == ""){
				e.preventDefault();
				error2.value="choose check in date"
			}
			if (CheckOut.value == ""){
				e.preventDefault();
				error3.value="choose check out date"
			}
		});
</script>

</body>

RailsProject/Booking/app/views/hotels/searchComment.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>


<form action="/searchComment" method="post">
  <fieldset>
    <legend>search for comment:</legend>
		<input type="text" id="h1" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Hotel Name:<input type="text" name="hotel" id="h" value=<%=@hotel%> >
		<input type="text" id="h2" style = "border: none;border-color: transparent;color:red; readonly">
		<br>
		Region:<input type="text" name="region" id="r" value=<%=@region%> >
		<br>	
		
		<input type="submit" value="Search" id="s">
	</fieldset>

</form>
<%=cookies[:error1] %>
<script>
		sub=document.getElementById("s");
		hotel = document.getElementById("h");
		region = document.getElementById("r");
		error1 = document.getElementById("h1");
		error2 = document.getElementById("h2");
		sub.addEventListener('click',function(e){
			error1.value=""
			error2.value=""
			if (hotel.value == ""){
				e.preventDefault();
				error1.value="enter the hotel name"
			}
				if (region.value == ""){
				e.preventDefault();
				error2.value="enter the region"
			}
		});
</script>

</html>

RailsProject/Booking/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Country:</b>
  <%= @hotel.country %>
</p>

<p>
  <b>City:</b>
  <%= @hotel.city %>
</p>

<p>
  <b>Region:</b>
  <%= @hotel.region %>
</p>

<p>
  <b>Name:</b>
  <%= @hotel.name %>
</p>

<p>
  <b>Address:</b>
  <%= @hotel.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @hotel.phone %>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>