RailsProject/Booking/config/routes.rb
Booking::Application.routes.draw do
  resources :reserves

  resources :signups

  resources :rooms

  resources :hotels

	match '/searchHotel', :to => 'hotels#search'
	match '/viewHotel', :to => 'hotels#found'
	match '/avilableRooms/:id', :to => 'rooms#found'
	match '/reservedRoom/:id', :to => 'rooms#reserved'
	match '/register', :to => 'signups#new'
	match '/login', :to => 'signups#login'
	match '/logout', :to => 'signups#logOut'
	match '/loginBook', :to => 'signups#loginBook'
	match '/loginComment', :to => 'signups#loginComment'
	match '/reserved', :to => 'rooms#reserved'
	match '/viewdetail/:id', :to => 'rooms#viewdetail'
	match '/addcomment/:id', :to => 'rooms#addcomment'
	match '/searchComment', :to => 'hotels#searchComment'
	match '/roomComment', :to => 'hotels#roomComment'

end

RailsProject/Booking/app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to:hotel
end

RailsProject/Booking/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

	def found

		if cookies[:country1]
			#session[:hotel_id]=params[:id]
			cookies[:hotel_id1] = { value: params[:id], expires: 1.hour.from_now }
			@rooms = Room.find_by_sql(["SELECT * FROM `rooms` where rooms.hotel_id=? and rooms.room_number not in (select reserves.room_id from reserves where check_in between ? and ? or check_out between ? and ? )",cookies[:hotel_id1],cookies[:checkIn1],cookies[:checkOut1] ,cookies[:checkIn1],cookies[:checkOut1] ])

		end
	end

#-----------------------------------------
	def reserved
		
			i=0
		@choice=params[:role_ids]

		if cookies[:hotel_id1]
		#	cookies[:room_id1] = params[:id]
			
			if cookies[:login].blank?
				@choice.each do |room|
					cookies[i] = { value: room, expires: 1.hour.from_now }
					i+=1
				end				
				cookies[:count]=i
				redirect_to url_for(:controller => 'signups',:action => 'loginBook')
			else
				
				@choice.each do |room|
					newParams={"user_id" => cookies[:login] , "hotel_id" => cookies[:hotel_id1], "room_id" => room, "check_in" => cookies[:checkIn1], "check_out" => cookies[:checkOut1] }
					@reserve = Reserve.new(newParams)
					@reserve.save
				end
					redirect_to url_for(:controller => 'hotels',:action => 'search')
			end
		else
				redirect_to url_for(:controller => 'hotels',:action => 'search')
		end		
	end
#---------------------------------------------------
	def viewdetail

		@room_id=params[:id]
		@room = Room.find_by_sql(["select * from rooms join hotels on hotel_id=hotels.id where hotel_id=? and room_number=?",cookies[:hotel_id1],params[:id]])
		@comments=Signup.find_by_sql(["SELECT c.* , s.* FROM  `comments` AS c INNER JOIN signups AS s ON c.user_id = s.id and hotel_id=? and room_id=?",cookies[:hotel_id1],params[:id]])


	end

#--------------------------------------
	def addcomment
			

			if cookies[:hotel_id1]
			#	cookies[:room_id1] = params[:id]
			
				if cookies[:login].blank?
					cookies[:room_id1] = params[:id]
					cookies[:comment1] = params[:comment]
					redirect_to url_for(:controller => 'signups',:action => 'loginComment')
				else
					newParams={"user_id" => cookies[:login] , "hotel_id" => cookies[:hotel_id1], "room_id" => params[:id], "comment" =>params[:comment] }
					@reserve = Comment.new(newParams)
					@reserve.save

					redirect_to url_for(:controller => 'hotels',:action => 'search')
				end
			else
					redirect_to url_for(:controller => 'hotels',:action => 'search')
			end	

	end
#----------------------------------------

end

RailsProject/Booking/app/helpers/rooms_helper.rb
module RoomsHelper
end

RailsProject/Booking/app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel_id %><br />
    <%= f.number_field :hotel_id %>
  </div>
  <div class="field">
    <%= f.label :room_number %><br />
    <%= f.number_field :room_number %>
  </div>
  <div class="field">
    <%= f.label :room_price %><br />
    <%= f.number_field :room_price %>
  </div>
  <div class="field">
    <%= f.label :room_discount %><br />
    <%= f.number_field :room_discount %>
  </div>
  <div class="field">
    <%= f.label :room_service %><br />
    <%= f.text_field :room_service %>
  </div>
  <div class="field">
    <%= f.label :room_image %><br />
    <%= f.text_field :room_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsProject/Booking/app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

RailsProject/Booking/app/views/rooms/found.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>


<form action="/reserved" method="post">
	<%= session[:hotel_id] %>
		
	<%= session[:checkIn] %>
	<% if @rooms.size > 0 %>
	<table border="1" style="width:300px">
	<tr>
		<td> Room Number </td>
		<td> Room Price </td>
		<td> Room Service </td>
	</tr>
		<% @rooms.each do |room| %>
			<tr>
				<td> <a href = "/viewdetail/<%= room.room_number%>"> <%= room.room_number%> </a> </td>
				<td>  <%= room.room_price%> </td>
				<td>  <%= room.room_service%> </td>		
				<td> <%= check_box_tag 'role_ids[]', room.room_number -%> </td>	
			</tr>
		<%end%>
		</table>
	<%else%>
		<a href="javascript:history.back()"> no hotel available in this country </a>
	<%end%>

<input type="submit" name="submit" value="reserved" id="s">
</form>

<script>
		ch = document.getElementsByName("role_ids[]")
		sub=document.getElementById("s");
		count=0
		sub.addEventListener('click',function(e){
				for (i=0;i<ch.length;i++){
					
					if(ch[i].checked==true){

						count++
					}
				}
				if (count == 0){
					e.preventDefault();
				}
		});

</script>


</html>

RailsProject/Booking/app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Hotel</th>
    <th>Room number</th>
    <th>Room price</th>
    <th>Room discount</th>
    <th>Room service</th>
    <th>Room image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.hotel_id %></td>
    <td><%= room.room_number %></td>
    <td><%= room.room_price %></td>
    <td><%= room.room_discount %></td>
    <td><%= room.room_service %></td>
    <td><%= room.room_image %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

RailsProject/Booking/app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

RailsProject/Booking/app/views/rooms/reserved.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

RailsProject/Booking/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hotel:</b>
  <%= @room.hotel_id %>
</p>

<p>
  <b>Room number:</b>
  <%= @room.room_number %>
</p>

<p>
  <b>Room price:</b>
  <%= @room.room_price %>
</p>

<p>
  <b>Room discount:</b>
  <%= @room.room_discount %>
</p>

<p>
  <b>Room service:</b>
  <%= @room.room_service %>
</p>

<p>
  <b>Room image:</b>
  <%= @room.room_image %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

RailsProject/Booking/app/views/rooms/viewdetail.html.erb
<html>
	<head>
	<style>
   html, body {
        background-color: white;
        color: black;
        font: 100%/1.25 sans-serif;
        margin: 0; 
        padding: 0;
        }
 
      p {
        font-size: 1em;
        }
 
      #wrapper {
        border: 1px dotted gray;
        margin: 20px auto 0;
        width: 90%;
        }
 
      #header {
        overflow: hidden;
        }
 
      #header h1 {
        float: left;
        margin-left: 60px;
        }
 
      #header ul {
        padding: 0;
        text-align: right;
        }
 
      #header li {
        border: 1px solid black;
        display: inline-block;
        margin: 1em .5em;
        text-align: left;
        }
 

	</style>
	</head>

<div id="wrapper">
      <div id="header">
				<h1>Booking</h1>searchHotel
			 
				<ul>
				<% if cookies[:login].blank? %>
					<li><a href="/login">Sign In</a></li>
			 
					<li><a href="/register">Sign Up</a></li>

					<%else%>

					<li><a href="/logout">Log Out</a></li>

				<%end%>

					
					
					<li><a href="/searchHotel">Booking</a></li>

					<li><a href="/searchComment">Comment</a></li>

				</ul>
      </div>    
</div>


<form action="/addcomment/<%=@room_id%>" method="post">
 	<% if @room %>
		<% @room.each do |rooms| %>
			<p> <font size=5> Hotel Name: <%=rooms.name%> </font></p>
			<img src=<%=rooms.room_image%>>
			<p> <font size=5> Room Price: <%=rooms.room_price%> </font></p>
			<p> <font size=5> Room Number: <%=rooms.room_number%> </font></p>
			<p> <font size=5> Room discount: <%=rooms.room_discount%> </font></p>
			<p> <font size=5> Comments: </font></p>

		<%end%>
			<% if @comments %>
				<% @comments.each do |comments| %>
					<p> <%=comments.name%> <p>
					<p> <%=comments.comment%> <p>	
				<%end%>
			<%end%>
						<p> <font size=3> write comment: </font></p>
			<textarea rows="4" cols="50" name="comment" id="comment"> </textarea>
		
	<%else%>
		<a href="javascript:history.back()"> no hotel available in this country </a>
	<%end%>
<br>
<input type="submit" name="submit" value="Comment" id="s">
</form>

<script>
		sub=document.getElementById("s");
		comment = document.getElementById("comment");
		sub.addEventListener('click',function(e){
			if (comment.value == " "){
				e.preventDefault();
			}
		});
</script>

</html>