RailsProject/Booking/config/routes.rb
Booking::Application.routes.draw do
  resources :reserves

  resources :signups

  resources :rooms

  resources :hotels

	match '/searchHotel', :to => 'hotels#search'
	match '/viewHotel', :to => 'hotels#found'
	match '/avilableRooms/:id', :to => 'rooms#found'
	match '/reservedRoom/:id', :to => 'rooms#reserved'
	match '/register', :to => 'signups#new'
	match '/login', :to => 'signups#login'
	match '/logout', :to => 'signups#logOut'
	match '/loginBook', :to => 'signups#loginBook'
	match '/loginComment', :to => 'signups#loginComment'
	match '/reserved', :to => 'rooms#reserved'
	match '/viewdetail/:id', :to => 'rooms#viewdetail'
	match '/addcomment/:id', :to => 'rooms#addcomment'
	match '/searchComment', :to => 'hotels#searchComment'
	match '/roomComment', :to => 'hotels#roomComment'

end

RailsProject/Booking/app/models/reserve.rb
class Reserve < ActiveRecord::Base
end

RailsProject/Booking/app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserve.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reserves }
    end
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
    @reserf = Reserve.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserf }
    end
  end

  # GET /reserves/new
  # GET /reserves/new.json
  def new
    @reserf = Reserve.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserf }
    end
  end

  # GET /reserves/1/edit
  def edit
    @reserf = Reserve.find(params[:id])
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserf = Reserve.new(params[:reserf])

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to @reserf, notice: 'Reserve was successfully created.' }
        format.json { render json: @reserf, status: :created, location: @reserf }
      else
        format.html { render action: "new" }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reserves/1
  # PUT /reserves/1.json
  def update
    @reserf = Reserve.find(params[:id])

    respond_to do |format|
      if @reserf.update_attributes(params[:reserf])
        format.html { redirect_to @reserf, notice: 'Reserve was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserf = Reserve.find(params[:id])
    @reserf.destroy

    respond_to do |format|
      format.html { redirect_to reserves_url }
      format.json { head :no_content }
    end
  end
end

RailsProject/Booking/app/helpers/reserves_helper.rb
module ReservesHelper
end

RailsProject/Booking/app/views/reserves/_form.html.erb
<%= form_for(@reserf) do |f| %>
  <% if @reserf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
      <% @reserf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :hotel_id %><br />
    <%= f.number_field :hotel_id %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br />
    <%= f.number_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :check_in %><br />
    <%= f.date_select :check_in %>
  </div>
  <div class="field">
    <%= f.label :check_out %><br />
    <%= f.date_select :check_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsProject/Booking/app/views/reserves/edit.html.erb
<h1>Editing reserf</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserf %> |
<%= link_to 'Back', reserves_path %>

RailsProject/Booking/app/views/reserves/index.html.erb
<h1>Listing reserves</h1>

<table>
  <tr>
    <th>User</th>
    <th>Hotel</th>
    <th>Room</th>
    <th>Check in</th>
    <th>Check out</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reserves.each do |reserf| %>
  <tr>
    <td><%= reserf.user_id %></td>
    <td><%= reserf.hotel_id %></td>
    <td><%= reserf.room_id %></td>
    <td><%= reserf.check_in %></td>
    <td><%= reserf.check_out %></td>
    <td><%= link_to 'Show', reserf %></td>
    <td><%= link_to 'Edit', edit_reserf_path(reserf) %></td>
    <td><%= link_to 'Destroy', reserf, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reserve', new_reserf_path %>

RailsProject/Booking/app/views/reserves/new.html.erb
<h1>New reserf</h1>

<%= render 'form' %>

<%= link_to 'Back', reserves_path %>

RailsProject/Booking/app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @reserf.user_id %>
</p>

<p>
  <b>Hotel:</b>
  <%= @reserf.hotel_id %>
</p>

<p>
  <b>Room:</b>
  <%= @reserf.room_id %>
</p>

<p>
  <b>Check in:</b>
  <%= @reserf.check_in %>
</p>

<p>
  <b>Check out:</b>
  <%= @reserf.check_out %>
</p>


<%= link_to 'Edit', edit_reserf_path(@reserf) %> |
<%= link_to 'Back', reserves_path %>